export type ResourceKey = 'food' | 'water' | 'meds' | 'radioPart' | 'wrench' | 'gasMask';

export type Inventory = Record<ResourceKey, number>;

export interface Stats {
  health: number;
  hunger: number;
  thirst: number;
  stress: number;
  morale: number;
  mood: number;
}

export interface Sickness {
  id: string;
  name: string;
  description: string;
  duration: number; // in days
  effects: {
    health?: number;
    hunger?: number;
    thirst?: number;
    stress?: number;
    morale?: number;
    mood?: number;
  };
  longTermEffects: string;
  cure: string;
  worsensTo?: string; // ID of the sickness it can progress to
}

export interface Character {
  id: string;
  name: string;
  description: string;
  stats: Stats;
  isAlive: boolean;
  sickness: Sickness | null;
}

export interface Choice {
  text: string;
  requiredItem?: ResourceKey;
  // The 'outcome' will be a text description generated by the AI
}

export interface GameEvent {
  eventTitle: string;
  eventDescription: string;
  choices: Choice[];
}

export interface StatChange {
    characterId: string;
    stat: keyof Stats;
    change: number; // can be positive or negative
}

export interface InventoryChange {
    item: ResourceKey;
    change: number; // can be positive or negative
}

export interface SicknessChange {
    characterId: string;
    sicknessId: string | 'none'; // ID from SICKNESSES object, or 'none' to cure
    duration?: number; // Optional override for sickness duration
}

export interface ShelterStateChange {
    property: keyof ShelterState;
    change?: number; // For numeric properties like durability
    value?: string; // For string properties like radiationLevel
    absolute?: boolean; // If true, sets the value directly instead of changing it
}

export interface Outcome {
    outcomeDescription: string;
    statChanges?: StatChange[];
    inventoryChanges?: InventoryChange[];
    sicknessChanges?: SicknessChange[];
    shelterStateChanges?: ShelterStateChange[];
}

export interface LogEntry {
    day: number;
    text: string;
    type: 'event' | 'choice' | 'outcome' | 'narration' | 'status' | 'dialogue' | 'scavenge' | 'radio';
}

export interface Notification {
    id: number;
    text: string;
    type: 'gain' | 'loss' | 'info';
}

export interface ShelterState {
    integrity: number;
    radioDurability: number;
    waterFilterDurability: number;
    radiationLevel: 'Bình thường' | 'Cao' | 'Nguy hiểm';
    airQuality: 'Tốt' | 'Kém' | 'Độc hại';
}

export interface GameState {
  characters: Character[];
  inventory: Inventory;
  shelterState: ShelterState;
  day: number;
  log: LogEntry[];
  currentEvent: GameEvent | null;
  gameOver: {
    isGameOver: boolean;
    isWin: boolean;
    message: string;
  };
  isLoading: boolean;
  gameStarted: boolean;
  intro: string;
  currentDialogue: string | null;
  canScavenge: boolean;
  talkedToToday: string[];
  scoutingCharacterId: string | null;
  radioUsedToday: boolean;
}
